FROM node:20

# Create and define the node_modules's cache directory.
WORKDIR /cache

# install app dependencies
COPY package*.json ./

RUN npm install

#set working directory
WORKDIR /app

# copy source code
COPY . .

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 3000

# CMD [ "npm", "run", "start" ]
