FROM node:16

#set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json .
RUN npm install

# copy source code
COPY . .

EXPOSE 3000

CMD [ "npm", "run", "start" ]