version: '3.8'

services:

  nest-api:
    container_name: nest-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    networks:
      - transendence

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5434:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - transendence
  
volumes:
  postgres:
    name: nest-db

networks:
  transendence:
    name: transendence
    driver: bridge