version: '3.8'

services:

# PROD-VERSION
  # nest-api:
  #   container_name: nest-api
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./backend/.env
  #   networks:
  #     - transendence

# DEV-VERSION
  nest-api:
    container_name: nest-api
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app/dev
      - ignore:/app/node_modules/
    networks:
      - transendence

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5434:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - transendence

# DEV-VERSION
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:3000
    depends_on:
      - postgres
      - nest-api
    # env_file:
    #   - ./frontend/.env
    volumes:
      - ./frontend/:/app
      - /app/node_modules/
    networks:
      - transendence
  
volumes:
  postgres:
    name: nest-db
  ignore: {}

networks:
  transendence:
    name: transendence
    driver: bridge