FROM node:20

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

WORKDIR /app/dev

COPY src ./src
COPY prisma ./prisma
COPY .env /

EXPOSE 3000

CMD [ "npm", "run", "start:dev" ]

