FROM node:20

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

# WORKDIR /app/dev

# COPY src ./src
# COPY prisma ./prisma
# COPY .env /

CMD [ "npm", "run", "start:dev" ]

